/**
 * Author: Arkady Zelensky
 */

module.exports = {
  SET_BOOKS: 'SET_BOOKS',
  ADD_NEW_BOOK: 'ADD_NEW_BOOK',
  DELETE_ONE_BOOK: 'DELETE_ONE_BOOK',
  EDIT_ONE_BOOK: 'EDIT_ONE_BOOK',

  SET_GENRES: 'SET_GENRES',
  ADD_NEW_GENRE: 'ADD_NEW_GENRE',
  DELETE_ONE_GENRE: 'DELETE_ONE_GENRE',
  EDIT_ONE_GENRE: 'EDIT_ONE_GENRE',

  SET_AUTHORS: 'SET_AUTHORS',
  ADD_NEW_AUTHOR: 'ADD_NEW_AUTHOR',
  DELETE_ONE_AUTHOR: 'DELETE_ONE_AUTHOR',
  EDIT_ONE_AUTHOR: 'EDIT_ONE_AUTHOR',

  SET_PAGE: 'SET_PAGE',
}